// app/engineer/scheduling/data.tsx
export const constructionData = {
  "Site Analysis & Preparation": [
    "Site Location And Access",
    "Road & Transportation Accessibility",
    "Water & Electricity Accessibility",
    "Land Surveying",
    "Topographical Survey (Contour,Slopes Map)",
    "Soil Investigation",
    "Site Clearance"
  ],
  "Design & Planning": [
    "Authorization & Sanctions From Government Bodies",
    "Contour Maps/Topographical Designs",
    "Architectural Designs",
    "Structural Designs",
    "3D Elevation Designs",
    "PEB/Fabrication Drawings",
    "Interior Design",
    "Electrical Drawings",
    "Plumbing & Sanitary Drawings",
    "HVAC Drawings",
    "Fire Fighting & Safety Drawings"
  ],
  "Foundation": {
    "Footing Schedule": [
      "Sight Out, Boundary Alignment & Dimensions Of Footing",
      "Excavation (Footing)",
      "Lead & Lift (Footing)",
      "Dewatering (Footing) If Needed",
      "Base Clearance (Footing)",
      "Soling & Compaction (Footing)",
      "P.C.C (Footing)",
      "Centerline Lineout (Footing)",
      "Footing B.B.S (Footing)",
      "Shuttering Of (Footing)",
      "Pedestal B.B.S & Erection On Footing",
      "Consultation Checking (Footing)",
      "Footing Casting (Footing)",
      "Footing De-shuttering (Footing)",
      "Centerline & Column Starter (Footing)",
      "Pedestal Shuttering (Footing)",
      "Pedestal Casting (Footing)",
      "Backfilling & Ground Levelling (Footing)",
      "Curing (Footing)",
      "Other (Footing)"
    ],
    "Raft/Mat Foundation Schedule": [
      "Sight Out, Boundary Alignment & Dimensions Of (Raft Foundation)",
      "Excavation (Raft Foundation)",
      "Lead & Lift (Raft Foundation)",
      "Dewatering (Raft Foundation) If Needed",
      "Base Clearance (Raft Foundation)",
      "Soling & Compaction (Raft Foundation)",
      "P.C.C/ Blinding Layer (Raft Foundation)",
      "Waterproofing (Raft Foundation)",
      "Centerline Lineout (Raft Foundation)",
      "Reinforcement Mesh (Raft Foundation)",
      "Shuttering/ Edges Or Boundaries Formwork (Raft Foundation)",
      "Consultation Checking (Raft Foundation)",
      "Casting (Raft Foundation)",
      "De-shuttering (Raft Foundation)",
      "Backfilling & Ground Levelling (Raft Foundation)",
      "Curing (Raft Foundation)",
      "Other (Raft Foundation)"
    ],
    "Pile/ Pier / Deep Foundation Schedule": [
      "Sight Out, Boundary Alignment & Dimensions Of (Pile/Pier Foundation)",
      "Setting Out/Centerline Lineout (Pile/Pier Foundation)",
      "Dewatering (Pile/Pier Foundation) If Needed",
      "Boring/Driving (Pile/Pier Foundation)",
      "Borehole Cleaning (Pile/Pier Foundation)",
      "Lead & Lift (Pile/Pier Foundation)",
      "Casing Fixing (Pile/Pier Foundation)",
      "Bentonite Placing (Pile/Pier Foundation)",
      "Reinforcement Cage BBS Making (Pile/Pier Foundation)",
      "Reinforcement Cage Placement (Pile/Pier Foundation)",
      "Consultation Checking (Pile/Pier Foundation)",
      "Precast Fixing (Pile/Pier Foundation)",
      "In Situ Casting (Pile/Pier Foundation)",
      "Casing Removing (Pile/Pier Foundation)",
      "Cap Fixing (Pile/Pier Foundation)",
      "Curing",
      "Others (Pile/Pier Foundation)"
    ]
  },
  "Beam": {
    "Ground/ Plinth Beam Schedule": [
      "Levelling (Ground/Plinth Beam)",
      "Compaction(Ground/Plinth Beam)",
      "Surface Dressing (Ground/Plinth Beam)",
      "P.C.C (Ground/Plinth Beam)",
      "Reinforcement (Ground/Plinth Beam)",
      "Formwork & Shuttering (Ground/Plinth Beam)",
      "Consultation Checking (Ground/Plinth Beam)",
      "Casting (Ground/Plinth Beam)",
      "De-shuttering (Ground/Plinth Beam)",
      "Curing (Ground/Plinth Beam)",
      "Others (Ground/Plinth Beam)"
    ],
    "Main/Slab/Sill/Lintel/ Roof Beam Schedule": [
      "Levelling (Beam)",
      "Bottom/Soffit/Cap Shuttering (Beam)",
      "Props/Support (Beam)",
      "Reinforcement B.B.S Fixing (Beam)",
      "Side Shuttering (Beam)",
      "Electrical/Plumbing Line Provisions (Beam)",
      "Consultation Checking (Beam)",
      "Casting (Beam)",
      "De-shuttering (Beam)",
      "Curing (Beam)",
      "Others (Beam)"
    ]
  },
  "Columns": {
    "Pedestal Column Schedule": [
      "Levelling (Pedestal Column)",
      "Sight Out, Centerline Alignment & Dimensions (Pedestal Column)",
      "Dewatering (Pedestal Column) If Needed",
      "Base Clearance (Pedestal Column)",
      "Starter (Pedestal Column)",
      "Reinforcement B.B.S (Pedestal Column)",
      "Shuttering & Formwork(Pedestal Column)",
      "Props/Support Fixing (Pedestal Column)",
      "Consultation Checking (Pedestal Column)",
      "Casting (Pedestal Column)",
      "De-shuttering (Pedestal Column)",
      "Curing (Pedestal Column)",
      "Others (Pedestal Column)"
    ],
    "Main Column Schedule": [
      "Levelling (Main Column)",
      "Sight Out, Centerline Alignment & Dimensions (Main Column)",
      "Base Clearance (Main Column)",
      "Starter (Main Column)",
      "Reinforcement B.B.S (Main Column)",
      "Shuttering & Formwork (Main Column)",
      "Props/Support Fixing (Main Column)",
      "Consultation Checking (Main Column)",
      "Casting (Main Column)",
      "De-shuttering (Main Column)",
      "Curing (Main Column)",
      "Others (Main Column)"
    ]
  },
  "Slab Work Schedule": [
    "Sight Out, Centerline Alignment & Dimensions (Slab Work)",
    "Bottom/Soffit/Cap Shuttering For Beams (Slab Work)",
    "Props/Support/Ledger Fixing For Beams (Slab Work)",
    "Reinforcement B.B.S Fixing For Beams (Slab Work)",
    "Props/Support/Ledger Fixing For Slab Base (Slab Work)",
    "Base Clearance For Slab (Slab Work)",
    "Levelling For Slab (Slab Work)",
    "Centre Plate/Surface Ply Laying For Slab Span (Slab Work)",
    "Reinforcement B.B.S/Slab Mesh  (Slab Work)",
    "Internal Plumbing & Electrical Lines Laying Before Casting Work Under Slab,Beam And R.C.C Units (Slab Work)",
    "Doweling Staircase Reinforcement BBS (Slab Work)",
    "Side Shuttering/Formwork For Beams (Slab Work)",
    "Consultation Checking (Slab Work)",
    "Arrangement Of T.M,Placer,Pumps And Casting Team (Slab Work)",
    "Casting (Slab Work)",
    "Surface Finishing (Slab Work)",
    "De-shuttering (Slab Work)",
    "Curing (Slab Work)",
    "Others (Slab Work)"
  ],
  "Staircase Work Schedule": [
    "Sight Out, Centerline Alignment & Dimensions (Staircase)",
    "Bottom Shuttering For Landing Slab & Walkway (Staircase)",
    "Props/Support/Ledger Fixing For Cantilever & Beams (Staircase)",
    "Reinforcement B.B.S Fixing For Staircase (Staircase)",
    "Side Shuttering/Formwork (Staircase)",
    "Internal Plumbing & Electrical Lines Laying Before Casting Work Under Staircase (Staircase)",
    "Doweling Staircase Reinforcement BBS For Slab (Staircase)",
    "Consultation Checking (Staircase)",
    "Casting (Staircase)",
    "Surface Finishing (Staircase)",
    "De-shuttering (Staircase)",
    "Curing (Staircase)",
    "Tiling/Stone Fixing (Staircase)",
    "Railing Fixing (Staircase)",
    "Others (Staircase)"
  ],
  
  "Plumbing Work Schedule": [
    "Boundary Alignment/Layout & Slope, Dimensions",
    "Material Procurement& Storage(Plumbing)",
    "External Trenches Excavation (Plumbing)",
    "Dewatering (Plumbing) If Needed",
    "Lead/Lift  (Plumbing)",
    "Base Clearance (Plumbing)",
    "Dressing & Slopping (Plumbing)",
    "Soling & Compaction (Plumbing)",
    "P.C.C (Plumbing)",
    "Centerline Lineout (Plumbing)",
    "Laying SWR/Rainwater Pipe Lines Below Slab (Plumbing)",
    "Joint Filling (Plumbing)",
    "Chamber Brickwork & Plaster (Plumbing)",
    "Consultation Checking (Plumbing)",
    "Leakage Test (Plumbing)",
    "Backfilling (Plumbing)",
    "Staging/Scaffolding (Plumbing)",
    "Vertical Sleeve Insertion During R.C.C Work (Plumbing)",
    "Main Risers & Ducts During R.C.C Work (Plumbing)",
    "Wall Chiseling For Internal Wall (Plumbing)",
    "Laying Concealed Water Lines CPVC, UPVC, PPR Pipes For Internal Wall (Plumbing)",
    "Consultation Checking (Plumbing)",
    "Leakage Test (Plumbing)",
    "Fixing Sanitary Fixtures (Plumbing)",
    "CP Fittings Installation (Plumbing)",
    "Leakage Test (Plumbing)",
    "Others (Plumbing)"
  ],
  "Electrical Work Schedule": [
    "Marking,Lineout &Dimensions (Electrical)",
    "Material Procurement& Storage(Electrical)",
    "Earthing & Grounding Work (Electrical)",
    "Cable Laying & Termination Work (Electrical)",
    "Internal Lines Laying Before Casting Work Under Slab,Beam And R.C.C Units (Electrical)",
    "Staging/Scaffolding (Electrical)",
    "Wall Chiseling (Electrical)",
    "Fixing Of PVC conduit,GI/EMT conduit,Cable Trays & Trunking (Electrical)",
    "Wiring Installation (Electrical)",
    "Switchboards and Distribution Panels (Electrical)",
    "Fixture and Devices Installation (Electrical)",
    "Smart Home Automation Setup (Electrical)",
    "Solar Power System Integration (Electrical)",
    "DG set & UPS Integration (Electrical)",
    "Fire Alarm & PA System Wiring (Electrical)",
    "CCTV & Access Control Installation (Electrical)",
    "Testing & Consultation (Electrical)",
    "Others (Electrical)"
  ],
  "Fireline Work Schedule": [
    "Marking,Lineout & Dimensions (Fireline Work)",
    "Coordination With Other Teams (Fireline Work)",
    "Material Procurement & Storage (Fireline Work)",
    "External Trenches Excavation (Fireline Work)",
    "Bed Preparation (Fireline Work)",
    "Centerline Lineout (Fireline Work)",
    "Pipe Laying (Fireline Work)",
    "Jointing (Fireline Work)",
    "Consultation Checking (Fireline Work)",
    "Leakage Test (Fireline Work)",
    "Backfilling (Fireline Work)",
    "Staging/Scaffolding (Fireline Work)",
    "Internal Fire Piping Riser/Downcomer Fixing (Fireline Work)",
    "Branch Line Connection & Valve Installation (Fireline Work)",
    "Sprinkler System Installation (If Needed) (Fireline Work)",
    "Hydrant System Installation (Fireline Work)",
    "Pump Room Installation (Fireline Work)",
    "Others (Fireline Work)"
  ],
  "Elevator /Lift Work Schedule": [
    "Marking,Lineout & Dimensions (Elevator Work)",
    "Coordination With Other Teams (Elevator Work)",
    "Material Procurement & Storage (Elevator Work)",
    "Civil Work Preparation Activities(Elevator Work)",
    "Lift Machine Room Work (Elevator Work)",
    "Staging/Scaffolding (Elevator Work)",
    "MEP Work Activities (Elevator Work)",
    "Guide Rail Brackets & Inserts Casting Installation (Elevator Work)",
    "Installation Of Traction Machine/Motor (Elevator Work)",
    "Counterweight Installation (Elevator Work)",
    "Car & Car Frame Assembly (Elevator Work)",
    "Wiring & Control Panel Setup (Elevator Work)",
    "Door Installation (Elevator Work)",
    "Consultation (Elevator Work)",
    "Safety & Certification (Elevator Work)",
    "Others (Elevator Work)"
  ],
  "Painting Work Schedule": [
    "Marking,Lineout & Dimensions (Painting Work)",
    "Coordination With Other Teams (Painting Work)",
    "Material Procurement & Storage (Painting Work)",
    "Staging/Scaffolding (Painting Work)",
    "Surface Preparation (Painting Work)",
    "Putty & Patching (Painting Work)",
    "Primer Application (Painting Work)",
    "First Coat/Base Coat (Painting Work)",
    "Drying & Surface Check (Painting Work)",
    "Second/Final Coat (Painting Work)",
    "Doors, Windows,Grill, Railings,Ceiling Work (Painting Work)",
    "Others (Painting Work)"
  ],

  "Road/Highway Work Schedule": [
    "Pre-construction Activities (Roadwork)",
    "Material Procurement (Roadwork)",
    "Testing & Checking (Roadwork)",
    "Utility Provisions (Roadwork)",
    "Tree Cutting & Relocation (Roadwork)",
    "Site Clearing & Grubbing (Roadwork)",
    "Survey,Boundary Alignment & Dimensions (Roadwork)",
    "Dewatering (Roadwork) If Needed",
    "Stripping of B.C/Topsoil (Roadwork)",
    "Cutting & Filling/Excavation (Roadwork)",
    "Lead & Lift (Roadwork)",
    "Subgrade Compaction (Roadwork)",
    "Retaining/Toe/Protection/Shear Walls (Roadwork)",
    "Reinforcement & Casting Work (Roadwork)",
    "Base Clearance (Roadwork)",
    "Granular Sub-base (GSB) Laying & Compaction Work (Roadwork)",
    "WBM/WMM Work (Roadwork)",
    "DBM Work (Roadwork)",
    "Prime Coat Application (Roadwork)",
    "Tack Coat Application (Roadwork)",
    "Bituminous Concrete (BC) Laying (Roadwork)",
    "Asphalt or Concrete Surfacing (Roadwork)",
    "Culverts Construction (Roadwork)",
    "Bridges and Flyovers (if applicable)",
    "Drainage Systems (Roadwork)",
    "Side Slopes and Pitching (Roadwork)",
    "Footpaths / Shoulders Construction (Roadwork)",
    "Kerb Stone Laying (Roadwork)",
    "Crash Barriers / Guardrails Installation (Roadwork)",
    "Sign Boards, Signals & Poles (Roadwork)",
    "Street Lighting (Roadwork)",
    "Road Markings (white/yellow lines) (Roadwork)",
    "Reflective Road Studs / Cat Eyes (Roadwork)",
    "Cleaning (Roadwork)",
    "Curing (Roadwork)",
    "Others (Roadwork)"
  ],
  "Culvert Work Schedule": [
    "Sight Out, Boundary Alignment & Dimensions Of (Culvert)",
    "Water Diversion (Culvert) If Needed",
    "Excavation (Culvert)",
    "Lead & Lift (Culvert)",
    "Dewatering/Seepage Reduction (Culvert) If Needed",
    "Base Clearance & Dressing (Culvert)",
    "Stone/GSB Layering (Culvert)",
    "Soling & Compaction (Culvert)",
    "P.C.C (Culvert)",
    "Coffer Dam Installation (Culvert) If Needed",
    "Piping & Seepage Reduction/Waterproofing (Culvert)",
    "Centerline Lineout & Marking (Culvert)",
    "Footing/Raft Reinforcement B.B.S (Culvert)",
    "Shuttering/Formwork (Culvert)",
    "Consultation Checking (Culvert)",
    "Footing Casting (Culvert)",
    "Pedestal Reinforcement B.B.S (Culvert)",
    "Pedestal Casting (Culvert)",
    "Curing (Culvert)",
    "Laying Of Precast RCC/HDPE For Pipes Culverts (Culvert)",
    "Joint Filling (Culvert)",
    "Top Slab Casting For Box Culverts (Culvert)",
    "Headwall Construction (Culvert)",
    "Backfilling & Vibration (Culvert)",
    "Weep Holes Work (Culvert)",
    "Stone Pitching/Riprap (Culvert)",
    "Approach Embankments/Ramps Construction (Culvert)",
    "Waterproofing (Culvert)",
    "Plastering (Culvert)",
    "Parapet walls/Railings/Guard stones Installation (Culvert)",
    "Water Passage Cleaning (Culvert)",
    "Others (Culvert)"
  ],
  "Footpath Work Schedule": [
    "Pre-construction Activities (Footpath)",
    "Dismantling Existing Footpath If Needed",
    "Material Procurement (Footpath)",
    "Utility Provisions (Footpath)",
    "Tree Cutting & Relocation (Footpath)",
    "Site Clearing & Grubbing (Footpath)",
    "Survey,Boundary Alignment & Dimensions (Footpath)",
    "Stripping of B.C/Topsoil (Footpath)",
    "Excavation (Footpath)",
    "Lead & Lift (Footpath)",
    "Subgrade Compaction (Footpath)",
    "Layering Of G.S.B & Compaction (Footpath)",
    "WMM/Concreting Layer (Footpath)",
    "Excavation & PCC For Kerb Stones (Footpath)",
    "Casting & Backfilling For Kerb Stones (Footpath)",
    "Sand Bedding (Footpath)",
    "Interlocking Paver Blocks Laying (Footpath)",
    "Joint Filling (Footpath)",
    "Cross Slope Or Camber Work (Footpath)",
    "Side Drains/Stormwater Inlets Work (Footpath)",
    "Bollards/Railing Installation (Footpath)",
    "Bench Installation (Footpath)",
    "Painting & Finishing Work (Footpath)",
    "Others (Footpath)"
  ]

}