// app/engineer/scheduling/data.tsx
export const constructionData = {
  "Site Analysis & Preparation": [
    "Site Location And Access",
    "Road & Transportation Accessibility",
    "Water & Electricity Accessibility",
    "Land Surveying",
    "Topographical Survey (Contour,Slopes Map)",
    "Soil Investigation",
    "Site Clearance"
  ],
  "Design & Planning": [
    "Authorization & Sanctions From Government Bodies",
    "Contour Maps/Topographical Designs",
    "Architectural Designs",
    "Structural Designs",
    "3D Elevation Designs",
    "PEB/Fabrication Drawings",
    "Interior Design",
    "Electrical Drawings",
    "Plumbing & Sanitary Drawings",
    "HVAC Drawings",
    "Fire Fighting & Safety Drawings"
  ],
  "Foundation": {
    "Footing Schedule": [
      "Sight Out, Boundary Alignment & Dimensions Of Footing",
      "Excavation (Footing)",
      "Lead & Lift (Footing)",
      "Dewatering (Footing) If Needed",
      "Base Clearance (Footing)",
      "Soling & Compaction (Footing)",
      "P.C.C (Footing)",
      "Centerline Lineout (Footing)",
      "Footing B.B.S (Footing)",
      "Shuttering Of (Footing)",
      "Pedestal B.B.S & Erection On Footing",
      "Consultation Checking (Footing)",
      "Footing Casting (Footing)",
      "Footing De-shuttering (Footing)",
      "Centerline & Column Starter (Footing)",
      "Pedestal Shuttering (Footing)",
      "Pedestal Casting (Footing)",
      "Backfilling & Ground Levelling (Footing)",
      "Curing (Footing)",
      "Other (Footing)"
    ],
    "Raft/Mat Foundation Schedule": [
      "Sight Out, Boundary Alignment & Dimensions Of (Raft Foundation)",
      "Excavation (Raft Foundation)",
      "Lead & Lift (Raft Foundation)",
      "Dewatering (Raft Foundation) If Needed",
      "Base Clearance (Raft Foundation)",
      "Soling & Compaction (Raft Foundation)",
      "P.C.C/ Blinding Layer (Raft Foundation)",
      "Waterproofing (Raft Foundation)",
      "Centerline Lineout (Raft Foundation)",
      "Reinforcement Mesh (Raft Foundation)",
      "Shuttering/ Edges Or Boundaries Formwork (Raft Foundation)",
      "Consultation Checking (Raft Foundation)",
      "Casting (Raft Foundation)",
      "De-shuttering (Raft Foundation)",
      "Backfilling & Ground Levelling (Raft Foundation)",
      "Curing (Raft Foundation)",
      "Other (Raft Foundation)"
    ],
    "Pile/ Pier / Deep Foundation Schedule": [
      "Sight Out, Boundary Alignment & Dimensions Of (Pile/Pier Foundation)",
      "Setting Out/Centerline Lineout (Pile/Pier Foundation)",
      "Dewatering (Pile/Pier Foundation) If Needed",
      "Boring/Driving (Pile/Pier Foundation)",
      "Borehole Cleaning (Pile/Pier Foundation)",
      "Lead & Lift (Pile/Pier Foundation)",
      "Casing Fixing (Pile/Pier Foundation)",
      "Bentonite Placing (Pile/Pier Foundation)",
      "Reinforcement Cage BBS Making (Pile/Pier Foundation)",
      "Reinforcement Cage Placement (Pile/Pier Foundation)",
      "Consultation Checking (Pile/Pier Foundation)",
      "Precast Fixing (Pile/Pier Foundation)",
      "In Situ Casting (Pile/Pier Foundation)",
      "Casing Removing (Pile/Pier Foundation)",
      "Cap Fixing (Pile/Pier Foundation)",
      "Curing",
      "Others (Pile/Pier Foundation)"
    ]
  },
  "Beam": {
    "Ground/ Plinth Beam Schedule": [
      "Levelling (Ground/Plinth Beam)",
      "Compaction(Ground/Plinth Beam)",
      "Surface Dressing (Ground/Plinth Beam)",
      "P.C.C (Ground/Plinth Beam)",
      "Reinforcement (Ground/Plinth Beam)",
      "Formwork & Shuttering (Ground/Plinth Beam)",
      "Consultation Checking (Ground/Plinth Beam)",
      "Casting (Ground/Plinth Beam)",
      "De-shuttering (Ground/Plinth Beam)",
      "Curing (Ground/Plinth Beam)",
      "Others (Ground/Plinth Beam)"
    ],
    "Main/Slab/Sill/Lintel/ Roof Beam Schedule": [
      "Levelling (Beam)",
      "Bottom/Soffit/Cap Shuttering (Beam)",
      "Props/Support (Beam)",
      "Reinforcement B.B.S Fixing (Beam)",
      "Side Shuttering (Beam)",
      "Electrical/Plumbing Line Provisions (Beam)",
      "Consultation Checking (Beam)",
      "Casting (Beam)",
      "De-shuttering (Beam)",
      "Curing (Beam)",
      "Others (Beam)"
    ]
  },
  "Columns": {
    "Pedestal Column Schedule": [
      "Levelling (Pedestal Column)",
      "Sight Out, Centerline Alignment & Dimensions (Pedestal Column)",
      "Dewatering (Pedestal Column) If Needed",
      "Base Clearance (Pedestal Column)",
      "Starter (Pedestal Column)",
      "Reinforcement B.B.S (Pedestal Column)",
      "Shuttering & Formwork(Pedestal Column)",
      "Props/Support Fixing (Pedestal Column)",
      "Consultation Checking (Pedestal Column)",
      "Casting (Pedestal Column)",
      "De-shuttering (Pedestal Column)",
      "Curing (Pedestal Column)",
      "Others (Pedestal Column)"
    ],
    "Main Column Schedule": [
      "Levelling (Main Column)",
      "Sight Out, Centerline Alignment & Dimensions (Main Column)",
      "Base Clearance (Main Column)",
      "Starter (Main Column)",
      "Reinforcement B.B.S (Main Column)",
      "Shuttering & Formwork (Main Column)",
      "Props/Support Fixing (Main Column)",
      "Consultation Checking (Main Column)",
      "Casting (Main Column)",
      "De-shuttering (Main Column)",
      "Curing (Main Column)",
      "Others (Main Column)"
    ]
  },
  "Slab Work Schedule": [
    "Sight Out, Centerline Alignment & Dimensions (Slab Work)",
    "Bottom/Soffit/Cap Shuttering For Beams (Slab Work)",
    "Props/Support/Ledger Fixing For Beams (Slab Work)",
    "Reinforcement B.B.S Fixing For Beams (Slab Work)",
    "Props/Support/Ledger Fixing For Slab Base (Slab Work)",
    "Base Clearance For Slab (Slab Work)",
    "Levelling For Slab (Slab Work)",
    "Centre Plate/Surface Ply Laying For Slab Span (Slab Work)",
    "Reinforcement B.B.S/Slab Mesh  (Slab Work)",
    "Internal Plumbing & Electrical Lines Laying Before Casting Work Under Slab,Beam And R.C.C Units (Slab Work)",
    "Doweling Staircase Reinforcement BBS (Slab Work)",
    "Side Shuttering/Formwork For Beams (Slab Work)",
    "Consultation Checking (Slab Work)",
    "Arrangement Of T.M,Placer,Pumps And Casting Team (Slab Work)",
    "Casting (Slab Work)",
    "Surface Finishing (Slab Work)",
    "De-shuttering (Slab Work)",
    "Curing (Slab Work)",
    "Others (Slab Work)"
  ],
  "Staircase Work Schedule": [
    "Sight Out, Centerline Alignment & Dimensions (Staircase)",
    "Bottom Shuttering For Landing Slab & Walkway (Staircase)",
    "Props/Support/Ledger Fixing For Cantilever & Beams (Staircase)",
    "Reinforcement B.B.S Fixing For Staircase (Staircase)",
    "Side Shuttering/Formwork (Staircase)",
    "Internal Plumbing & Electrical Lines Laying Before Casting Work Under Staircase (Staircase)",
    "Doweling Staircase Reinforcement BBS For Slab (Staircase)",
    "Consultation Checking (Staircase)",
    "Casting (Staircase)",
    "Surface Finishing (Staircase)",
    "De-shuttering (Staircase)",
    "Curing (Staircase)",
    "Tiling/Stone Fixing (Staircase)",
    "Railing Fixing (Staircase)",
    "Others (Staircase)"
  ]
}