// data.ts
export type ConstructionData = {
  [mainTopic: string]: string[] | { [subTopic: string]: string[] };
};

export const constructionData: ConstructionData = {
  
  "Site Analysis & Preparation": [
    "Site Location And Access",
    "Road & Transportation Accessibility",
    "Water & Electricity Accessibility",
    "Land Surveying",
    "Topographical Survey (Contour,Slopes Map)",
    "Soil Investigation",
    "Site Clearance"
  ],
  "Design & Planning": [
    "Authorization & Sanctions From Government Bodies",
    "Contour Maps/Topographical Designs",
    "Architectural Designs",
    "Structural Designs",
    "3D Elevation Designs",
    "PEB/Fabrication Drawings",
    "Interior Design",
    "Electrical Drawings",
    "Plumbing & Sanitary Drawings",
    "HVAC Drawings",
    "Fire Fighting & Safety Drawings"
  ],
  "Foundation": {
    "Footing Schedule (Isolated/Combined/Strap/Continuous)": [
      "Sight Out, Boundary Alignment & Dimensions Of Footing",
      "Excavation (Footing)",
      "Lead & Lift (Footing)",
      "Dewatering (Footing) If Needed",
      "Base Clearance (Footing)",
      "Soling & Compaction (Footing)",
      "P.C.C (Footing)",
      "Centerline Lineout (Footing)",
      "Footing B.B.S (Footing)",
      "Shuttering Of (Footing)",
      "Pedestal B.B.S & Erection On Footing",
      "Consultation Checking (Footing)",
      "Footing Casting (Footing)",
      "Footing De-shuttering (Footing)",
      "Centerline & Column Starter (Footing)",
      "Pedestal Shuttering (Footing)",
      "Pedestal Casting (Footing)",
      "Backfilling & Ground Levelling (Footing)",
      "Curing (Footing)",
      "Other (Footing)"
    ],
    "Raft/Mat Foundation Schedule": [
      "Sight Out, Boundary Alignment & Dimensions Of (Raft Foundation)",
      "Excavation (Raft Foundation)",
      "Lead & Lift (Raft Foundation)",
      "Dewatering (Raft Foundation) If Needed",
      "Base Clearance (Raft Foundation)",
      "Soling & Compaction (Raft Foundation)",
      "P.C.C/ Blinding Layer (Raft Foundation)",
      "Waterproofing (Raft Foundation)",
      "Centerline Lineout (Raft Foundation)",
      "Reinforcement Mesh (Raft Foundation)",
      "Shuttering/ Edges Or Boundaries Formwork (Raft Foundation)",
      "Consultation Checking (Raft Foundation)",
      "Casting (Raft Foundation)",
      "De-shuttering (Raft Foundation)",
      "Backfilling & Ground Levelling (Raft Foundation)",
      "Curing (Raft Foundation)",
      "Other (Raft Foundation)"
    ],
    "Pile/ Pier / Deep Foundation Schedule": [
      "Sight Out, Boundary Alignment & Dimensions Of (Pile/Pier Foundation)",
      "Setting Out/Centerline Lineout (Pile/Pier Foundation)",
      "Dewatering (Pile/Pier Foundation) If Needed",
      "Boring/Driving (Pile/Pier Foundation)",
      "Borehole Cleaning (Pile/Pier Foundation)",
      "Lead & Lift (Pile/Pier Foundation)",
      "Casing Fixing (Pile/Pier Foundation)",
      "Bentonite Placing (Pile/Pier Foundation)",
      "Reinforcement Cage BBS Making (Pile/Pier Foundation)",
      "Reinforcement Cage Placement (Pile/Pier Foundation)",
      "Consultation Checking (Pile/Pier Foundation)",
      "Precast Fixing (Pile/Pier Foundation)",
      "In Situ Casting (Pile/Pier Foundation)",
      "Casing Removing (Pile/Pier Foundation)",
      "Cap Fixing (Pile/Pier Foundation)",
      "Curing",
      "Others (Pile/Pier Foundation)"
    ]
  },
  "Beam": {
    "Ground/ Plinth Beam Schedule": [
      "Levelling (Ground/Plinth Beam)",
      "Compaction(Ground/Plinth Beam)",
      "Surface Dressing (Ground/Plinth Beam)",
      "P.C.C (Ground/Plinth Beam)",
      "Reinforcement (Ground/Plinth Beam)",
      "Formwork & Shuttering (Ground/Plinth Beam)",
      "Consultation Checking (Ground/Plinth Beam)",
      "Casting (Ground/Plinth Beam)",
      "De-shuttering (Ground/Plinth Beam)",
      "Curing (Ground/Plinth Beam)",
      "Others (Ground/Plinth Beam)"
    ],
    "Main/Slab/Sill/Lintel/ Roof Beam Schedule": [
      "Levelling (Beam)",
      "Bottom/Soffit/Cap Shuttering (Beam)",
      "Props/Support (Beam)",
      "Reinforcement B.B.S Fixing (Beam)",
      "Side Shuttering (Beam)",
      "Electrical/Plumbing Line Provisions (Beam)",
      "Consultation Checking (Beam)",
      "Casting (Beam)",
      "De-shuttering (Beam)",
      "Curing (Beam)",
      "Others (Beam)"
    ]
  },
  "Columns": {
    "Pedestal Column Schedule": [
      "Levelling (Pedestal Column)",
      "Sight Out, Centerline Alignment & Dimensions (Pedestal Column)",
      "Dewatering (Pedestal Column) If Needed",
      "Base Clearance (Pedestal Column)",
      "Starter (Pedestal Column)",
      "Reinforcement B.B.S (Pedestal Column)",
      "Shuttering & Formwork(Pedestal Column)",
      "Props/Support Fixing (Pedestal Column)",
      "Consultation Checking (Pedestal Column)",
      "Casting (Pedestal Column)",
      "De-shuttering (Pedestal Column)",
      "Curing (Pedestal Column)",
      "Others (Pedestal Column)"
    ],
    "Main Column Schedule": [
      "Levelling (Main Column)",
      "Sight Out, Centerline Alignment & Dimensions (Main Column)",
      "Base Clearance (Main Column)",
      "Starter (Main Column)",
      "Reinforcement B.B.S (Main Column)",
      "Shuttering & Formwork (Main Column)",
      "Props/Support Fixing (Main Column)",
      "Consultation Checking (Main Column)",
      "Casting (Main Column)",
      "De-shuttering (Main Column)",
      "Curing (Main Column)",
      "Others (Main Column)"
    ]
  },
  "Slab Work Schedule": [
    "Sight Out, Centerline Alignment & Dimensions (Slab Work)",
    "Bottom/Soffit/Cap Shuttering For Beams (Slab Work)",
    "Props/Support/Ledger Fixing For Beams (Slab Work)",
    "Reinforcement B.B.S Fixing For Beams (Slab Work)",
    "Props/Support/Ledger Fixing For Slab Base (Slab Work)",
    "Base Clearance For Slab (Slab Work)",
    "Levelling For Slab (Slab Work)",
    "Centre Plate/Surface Ply Laying For Slab Span (Slab Work)",
    "Reinforcement B.B.S/Slab Mesh (Slab Work)",
    "Internal Plumbing & Electrical Lines Laying Before Casting Work Under Slab,Beam And R.C.C Units (Slab Work)",
    "Doweling Staircase Reinforcement BBS (Slab Work)",
    "Side Shuttering/Formwork For Beams (Slab Work)",
    "Consultation Checking (Slab Work)",
    "Arrangement Of T.M,Placer,Pumps And Casting Team (Slab Work)",
    "Casting (Slab Work)",
    "Surface Finishing (Slab Work)",
    "De-shuttering (Slab Work)",
    "Curing (Slab Work)",
    "Others (Slab Work)"
  ],
  "Staircase Work Schedule": [
    "Sight Out, Centerline Alignment & Dimensions (Staircase)",
    "Bottom Shuttering For Landing Slab & Walkway (Staircase)",
    "Props/Support/Ledger Fixing For Cantilever & Beams (Staircase)",
    "Reinforcement B.B.S Fixing For Staircase (Staircase)",
    "Side Shuttering/Formwork (Staircase)",
    "Internal Plumbing & Electrical Lines Laying Before Casting Work Under Staircase (Staircase)",
    "Doweling Staircase Reinforcement BBS For Slab (Staircase)",
    "Consultation Checking (Staircase)",
    "Casting (Staircase)",
    "Surface Finishing (Staircase)",
    "De-shuttering (Staircase)",
    "Curing (Staircase)",
    "Tiling/Stone Fixing (Staircase)",
    "Railing Fixing (Staircase)",
    "Others (Staircase)"
  ],
  "R.C Raft/R.C Wall Schedule": [
    "Sight Out, Boundary Alignment & Dimensions (R.C Raft/Wall)",
    "Excavation (R.C Raft/Wall)",
    "Lead & Lift (R.C Raft/Wall)",
    "Dewatering (R.C Raft/Wall) If Needed",
    "Staging/Scaffolding (R.C Raft/Wall)",
    "Base Clearance (R.C Raft/Wall)",
    "Soling & Compaction (R.C Raft/Wall)",
    "P.C.C (R.C Raft/Wall)",
    "Centerline Lineout (R.C Raft/Wall)",
    "Reinforcement B.B.S (R.C Raft/Wall)",
    "Shuttering/Formwork(R.C Raft/Wall)",
    "Reinforcement Column Placing (R.C Raft/Wall)",
    "Consultation Checking (R.C Raft/Wall)",
    "Casting (R.C Raft/Wall)",
    "De-shuttering (R.C Raft/Wall)",
    "Backfilling & Ground Levelling (R.C Raft/Wall)",
    "Safety Grill/Fencing (R.C Raft/Wall)",
    "Curing (R.C Raft/Wall)",
    "Other (R.C Raft/Wall)"
  ],
  "Trimix Work Schedule": [
    "Sight Out, Boundary Alignment & Dimensions (Trimix)",
    "Pocket Fixing (Trimix)",
    "Electrical Conduits & Plumbing Sleeves (Trimix)",
    "Trench Casting (Trimix) If Needed",
    "Base Clearance (Trimix)",
    "Surface Preparation (Trimix)",
    "Sheet/Polythene Placing (Trimix)",
    "Tarpaulin Fixing (Trimix)",
    "Level/Channel Setting",
    "Shuttering/Formwork (Trimix)",
    "Floating (Trimix)",
    "Vacuum Dewatering (Trimix)",
    "Troweling (Trimix)",
    "Hardener Application (Trimix)",
    "Curing (Trimix)",
    "Others (Trimix)"
  ],
  "PEB/Fabrication Work Schedule": {
    "Pedestal PEB/ Fabrication Column Schedule": [
      "Levelling (PEB Pedestal Column)",
      "Sight Out, Centerline Alignment & Dimensions (PEB Pedestal Column)",
      "Dewatering (PEB Pedestal Column) If Needed",
      "Base Clearance (PEB Pedestal Column)",
      "Starter(PEB Pedestal Column)",
      "Reinforcement B.B.S (PEB Pedestal Column)",
      "Shuttering & Formwork(PEB Pedestal Column)",
      "Props/Support Fixing (PEB Pedestal Column)",
      "Template & Bolt Fixing (PEB Pedestal Column)",
      "Consultation Checking (PEB Pedestal Column)",
      "Casting (PEB Pedestal Column)",
      "De-shuttering (PEB Pedestal Column)",
      "Template Removing (PEB Pedestal Column)",
      "Greasing/Bolt Covering (PEB Pedestal Column)",
      "Curing (PEB Pedestal Column)",
      "Others (PEB Pedestal Column)"
    ],
    "PEB Column Schedule": [
      "Column Delivery & Storage (PEB Column)",
      "Unloading (PEB Column)",
      "Inspection (PEB Column)",
      "Levelling (PEB Column)",
      "Sight Out, Centerline Alignment & Dimensions (PEB Column)",
      "Base Clearance (PEB Column)",
      "Bolt Clearing (PEB Column)",
      "Anti- Rust Coating (PEB Column)",
      "Erection (PEB Column)",
      "Consultation Checking (PEB Column)",
      "Torque Wrenching (PEB Column)",
      "Grouting/GP2 Filling (PEB Column)",
      "DFT/Patching (PEB Column)",
      "Curing (PEB Column)",
      "Others (PEB Column)"
    ],
    "PEB Raftar Schedule": [
      "Raftar Delivery & Storage (PEB Raftar)",
      "Unloading (PEB Raftar)",
      "Inspection (PEB Raftar)",
      "Levelling (PEB Raftar)",
      "Lifting & Erection (PEB Raftar)",
      "Splice Joint Connection (PEB Raftar)",
      "Alignment & Leveling (PEB Raftar)",
      "Torque Wrenching (PEB Raftar)",
      "Bracing (PEB Raftar)",
      "Sag Roads (PEB Raftar)",
      "Purlin (PEB Raftar)",
      "Others (PEB Raftar)"
    ],
    "PEB Roofing/Cladding/Louvers Schedule": [
      "SSR Machine Deployment (PEB Roofing)",
      "Sheet Cladding (PEB Roofing)",
      "Roof Sheeting Fixing (PEB Roofing)",
      "Side & End Wall Cladding (PEB Roofing)",
      "Gutter & Downspout Installation (PEB Roofing)",
      "Ridge Vent or Skylight (PEB Roofing)",
      "Trim & Flashing Installation (PEB Roofing)",
      "Doors & Windows Fixing (PEB Roofing)",
      "Turbo Vent / Louvers Installation (PEB Roofing)",
      "Painting / Coating Touchups (PEB Roofing)",
      "Leakage Test (PEB Roofing)",
      "Others (PEB Roofing)"
    ]
  },
  "Masonry Work Schedule": {
    "Brickwork Masonry Schedule": [
      "Levelling (Brickwork)",
      "Bricks Delivery & Storage (Brickwork)",
      "Sight Out, Centerline Alignment & Dimensions (Brickwork)",
      "Clearance (Brickwork)",
      "Soaking (Brickwork)",
      "Staging/Scaffolding (Brickwork)",
      "Layering (Brickwork)",
      "Consultation Checking (Brickwork)",
      "Brickwork Upto Sill Level (Brickwork)",
      "Sill Beam Casting (Brickwork)",
      "Brickwork Upto Lintel Level (Brickwork)",
      "Lintel Beam Casting (Brickwork)",
      "Brick Bat Coba or Beam Integration (Brickwork)",
      "Electrical Conduits & Plumbing Sleeves (Brickwork)",
      "Top Beam/Coping (Brickwork)",
      "Curing (Brickwork)",
      "Others (Brickwork)"
    ],
    "Stone/U.C.R Masonry Schedule": [
      "Levelling (Stone Masonry)",
      "Material Procurement (Stone Masonry)",
      "Sight Out, Centerline Alignment & Dimensions (Stone Masonry)",
      "Clearance (Stone Masonry)",
      "Stone Dressing / Shaping (Stone Masonry)",
      "Soaking (Stone Masonry)",
      "Staging/Scaffolding (Stone Masonry)",
      "Layering (Stone Masonry)",
      "Consultation Checking (Stone Masonry)",
      "Stonework Upto Certain Level (Stone Masonry)",
      "Tie Beam/Beam Integration (Stone Masonry)",
      "Electrical Conduits & Plumbing Sleeves (Stone Masonry)",
      "Pointing/Finishing (Stone Masonry)",
      "Top Beam/Coping (Stone Masonry)",
      "Curing (Stone Masonry)",
      "Others (Stone Masonry)"
    ]
  },
  "Plaster Work Schedule": [
    "Surface Preparation/Wetting (Plaster)",
    "Material Procurement (Plaster)",
    "Staging/Scaffolding (Plaster)",
    "Hatching/Racking Joints (Plaster)",
    "First Coat (Plaster)",
    "Secondary Coat (Plaster)",
    "Final/Edge Finishing (Plaster)",
    "Lime Finishing (Plaster)",
    "Curing (Plaster)",
    "Others (Plaster)"
  ],
  "Tiling Work Schedule": [
    "Levelling (Tiling Work)",
    "Material Procurement (Tiling Work)",
    "Sight Out, Centerline Alignment & Dimensions (Tiling Work)",
    "Clearance (Tiling Work)",
    "Stone Dressing / Shaping (Tiling Work)",
    "Soaking (Tiling Work)",
    "Base Preparation (Tiling Work)",
    "Grouting (Tiling Work)",
    "Cleaning (Tiling Work)",
    "Curing (Tiling Work)",
    "Others (Tiling Work)"
  ],
  "STP/ETP Work Schedule": [
    "Sight Out, Boundary Alignment & Dimensions (STP/ETP)",
    "Excavation (STP/ETP)",
    "Lead & Lift (STP/ETP)",
    "Dewatering (STP/ETP) If Needed",
    "Shoring & Supporting (STP/ETP) If Needed",
    "Base Clearance (STP/ETP)",
    "Soling & Compaction (STP/ETP)",
    "P.C.C (STP/ETP)",
    "Centerline Lineout (STP/ETP)",
    "R.C.C Raft/Walls/Footing B.B.S (STP/ETP)",
    "Shuttering/Formwork (STP/ETP)",
    "R.C.C Raft/Walls/Footing Casting (STP/ETP)",
    "Raft & Walls Waterproofing (STP/ETP)",
    "Tank Construction & Installation (STP/ETP)",
    "Internal Plaster & Lining (STP/ETP)",
    "Curing (STP/ETP)",
    "Pipeline/PVC/HDPE/CI/Effluent/Overflow Lines Work (STP/ETP)",
    "Oil & Grease Traps/ Manholes/Inspection Chamber Work (STP/ETP)",
    "Equipment Foundations Work (STP/ETP)",
    "Diffusers/Blowers,Clarifier, Sludge Beds,Filters,MBBR/MBR/SAFF Units Installation (STP/ETP)",
    "Pumps & Piping Work (STP/ETP)",
    "Panel Board Installation Work (STP/ETP)",
    "Cabling & Wiring (STP/ETP)",
    "Instrumentation Work (STP/ETP)",
    "Consultation Checking (STP/ETP)",
    "Others (STP/ETP)"
  ],
  "Breaking & Demolition Work Schedule": [
    "Site Inspection & Safety Setup (Breaking & Demolition)",
    "Utility Disconnection (Breaking & Demolition)",
    "Equipment & Machine Procurement (Breaking & Demolition)",
    "Marking & Fixing Dimensions (Breaking & Demolition)",
    "Dewatering (STP/ETP) If Needed (Breaking & Demolition)",
    "Breaking Process (Breaking & Demolition)",
    "Debris Lead & Lift/Reuse (Breaking & Demolition)",
    "Cleaning (Breaking & Demolition)"
  ]
}
export function validateConstructionData(data: ConstructionData): boolean {
  return Object.values(data).every((value) => {
    if (Array.isArray(value)) {
      return value.length > 0 && value.every((task) => typeof task === "string" && task.length > 0);
    } else if (typeof value === "object" && value !== null) {
      return Object.values(value).every(
        (subValue) =>
          Array.isArray(subValue) &&
          subValue.length > 0 &&
          subValue.every((task) => typeof task === "string" && task.length > 0)
      );
    }
    return false;
  });
}